### ISSUE TITLE
Bug: Change Garage Button does not work due to nested Layouts

### ISSUE THREAD

**Issue by a3rosol** [chrissijan/parking#28]

**Comment by chrissijan** [comment]
working at my end

**Comment by a3rosol** [comment]
is it still working on ui-branch?

**Comment by chrissijan** [comment]
idk didnt check.
not my problem after all

**Comment by a3rosol** [comment]
Still, please test new merged app

-- 
Emil Abramov
Sent with Airmail

Am 26. Juni 2015 bei 07:37:17, Christian (notifications@github.com) schrieb:

idk didnt check.
not my problem after all
